### ISSUE TITLE
Aspect Ratio Strech

### ISSUE THREAD

**Issue by madcat144** [Flupster/minustentv#18]
![black space](https://user-images.githubusercontent.com/25700170/94360170-5c47c580-0060-11eb-86ce-8ab8b4197631.PNG)

Floppy, there is way way way way to much black space on the top and bottom of the frame. This issue has not just been with image from the movie I linked. Its been with every movie. 

There's no need for that much negative space. 

xoxo

Madcat144

Fix this shit!

**Comment by Flupster** [comment]
Generally speaking movies are shot at an aspect ratio and are ment to played back at the same aspect ratio otherwise you stretch the entire image

Stretching is available in many media players so maybe I'll add this as an option in the future but it's low on priority atm

**Comment by Flupster** [comment]
It's there now madcat, but don't use it! movies/tv are ment to be watched in the aspect ratio they were mastered in!
