### ISSUE TITLE
Video playback rate to sync with live-edge

### ISSUE THREAD

**Issue by Emopants** [Flupster/minustentv#3]
Wouldn't it be great if sometimes the music in movies went all wonky like waa wooo waa waa wooo woo woo? It would be. It turns out it would be absolutely hilarious. Especially in serious movies with pretty dramatic scores. In fact, just make an option that allows all music to have that feature so that every tragedy or drama can be an instant comedy.

**Comment by jeffraider** [comment]
Uh no??!?!?!
